<?php
use Drupal\charts\Charts\ModuleSelector;

function webform_charts_theme() {
  $vars = [
    'library' => '',
    'categories' => '',
    'seriesData' => '',
    'options' => '',
  ];
  return [
    'charts_webform' => [
      'template' => 'charts_webform',
      'variables' => $vars,
    ],
  ];
}


/**
 * Implements template_preprocess_page
 *
 * @param $variables
 */
function template_preprocess_charts_webform(&$variables) {
  $moduleSelector = new ModuleSelector($variables['library'], $variables['categories'], $variables['seriesData'], $variables['options'], [], $variables, $variables['options']['id']);
}
